_name_: doublet
dataset_name: doublet
study_dir: '/your/data/directory'
cls_key: 'celltype'
add_eos: False
batch_size: 16
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 4
shuffle: True
pin_memory: True

# Lau
studies: ['Lau_2020_PNAS']
__train_len: 97_697
# studies: ['Lau_2020_PNAS_simul']
# __train_len: 98_074
# Leng
# studies: ['Leng_2021_Nat_Neurosci']
# __train_len: 41_560
# studies: ['Leng_2021_Nat_Neurosci_simul']
# __train_len: 42_836
# Smajic
# studies: ['Smajic_2022_brain']
# __train_len: 29_824
# studies: ['Smajic_2022_brain_simul']
# __train_len: 31_457
# Zhu
# studies: ['Zhu_2022_bioRxiv']
# __train_len: 53_358
# studies: ['Zhu_2022_bioRxiv_simul']
# __train_len: 55_834
# Jung
# studies: ['Jung_2022_unpublished']
# __train_len: 353_064